language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb+srv://ceibro:Appleapple1829@cluster0.t0y9jgi.mongodb.net/?retryWrites=true&w=majority
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
